pool:
  name: Hosted Ubuntu 1604
trigger:
  batch: true
  branches:
    include: 
      - tag/lts
  paths:
    exclude:
      - ReadMe.md
variables:
  tag: lts
steps:
- task: Docker@0
  displayName: 'Build TFX development image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: '$(registry-service-connection-name)'
    imageName: '$(docker-account)/$(image-name):$(tag)'
- task: Docker@0
  displayName: 'Push image to Docker Hub'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: '$(registry-service-connection-name)'
    action: 'Push an image'
    imageName: 'matthewdb/tfx-development:LTS'